### ISSUE TITLE
ChunkSpawnerLimiter stops working under Spigot 1.12

### ISSUE THREAD

**Issue by Sandukhan** [Cyprias/ChunkSpawnerLimiter#11]
ChunkSpawnerLimiter seems to be no longer runnable under Spigot 1.12
The reason for that you might find here:
https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-12.246398/

"Bukkit plugins which have not been updated in > 3 years and use deprecated features may be broken by routine API removals."

`[16:04:28 INFO]: [ChunkSpawnerLimiter] Enabling ChunkSpawnerLimiter v3.0.4
[16:04:28 ERROR]: Error occurred while enabling ChunkSpawnerLimiter v3.0.4 (Is it up to date?)
java.lang.NoSuchMethodError: com.cyprias.ChunkSpawnerLimiter.YML.load(Ljava/io/InputStream;)V
	at com.cyprias.ChunkSpawnerLimiter.YML.<init>(YML.java:17) ~[?:?]
	at com.cyprias.ChunkSpawnerLimiter.Config.checkForMissingProperties(Config.java:36) ~[?:?]
	at com.cyprias.ChunkSpawnerLimiter.Plugin.onEnable(Plugin.java:43) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot_server.jar:git-Spigot-cd6ba67-a7d074c]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot_server.jar:git-Spigot-cd6ba67-a7d074c]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot_server.jar:git-Spigot-cd6ba67-a7d074c]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot_server.jar:git-Spigot-cd6ba67-a7d074c]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot_server.jar:git-Spigot-cd6ba67-a7d074c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot_server.jar:git-Spigot-cd6ba67-a7d074c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot_server.jar:git-Spigot-cd6ba67-a7d074c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot_server.jar:git-Spigot-cd6ba67-a7d074c]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot_server.jar:git-Spigot-cd6ba67-a7d074c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot_server.jar:git-Spigot-cd6ba67-a7d074c]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]`

**Comment by sarhatabaot** [comment]
This doesn't work in this version. However I've fixed it in my [fork](https://github.com/sarhatabaot/ChunkSpawnerLimiter) of the plugin. (1.13.2)

**Comment by Sandukhan** [comment]
Always good to see other poeple willing to support old plugins, but there is also a fork from Jikoo that works with the 1.13.2 and also had some addintional changes. Maybe you wanna take a look on that and see if anything is diffrent there.

https://github.com/Jikoo/ChunkSpawnerLimiter
